### ISSUE TITLE
Image and zip support

### ISSUE THREAD

**Issue by briancullinan** [wader/fq#34]
This looks great, reminds me of 
https://arcan-fe.com/2017/10/05/awk-for-realtime-multimedia/

and this class I used to use in PHP.

http://getid3.sourceforge.net/

Might be useful for reference and supports tons of formats.

**Comment by wader** [comment]
Hello, thanks! fq has rudimentary zip and some images format (png, jpeg, tiff, webp) support already  but maybe you have run into some file that fq fails on for some reason? if that is the case if possible you could attach an example file in this issue? would be very helpful.

Thanks for the links. I tried to find arcane-fe but search results where confusing, have a link to it?

**Comment by wader** [comment]
Thanks for updating with link, now i see what you mean about pipeline. I early on did some prototyping to make fq work like this `fq file | jq ... | fq` so that fq would output some kind of "rich" json that you could filter with jq (or other things) and if you made sure to keep the rich stuff you could pipe it into fq again and make it slice up the file etc. But it felt clunky and the "rich" JSON become very verbose and hard to work with.

What did you mean by image and zip support btw? something else than the existing image and zip decoders in fq?

**Comment by wader** [comment]
Think i will close this for now, feel free to reopen or create a new issue if i misunderstood something
